version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "vue",
    "ember",
    "meteor",
    "angular",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]